# Generated by Django 5.0.2 on 2024-08-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
